# Generated by Django 2.0.2 on 2018-02-15 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('favoritesongs', '0002_auto_20180213_1418'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Favorite',
            new_name='FavoriteSong',
        ),
        migrations.RenameField(
            model_name='favoritesong',
            old_name='song',
            new_name='song_id',
        ),
        migrations.RenameField(
            model_name='favoritesong',
            old_name='user',
            new_name='user_id',
        ),
    ]
