# Generated by Django 2.0.2 on 2018-02-15 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('favoritesongs', '0004_auto_20180215_1551'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favoritesong',
            name='song',
        ),
        migrations.RemoveField(
            model_name='favoritesong',
            name='user',
        ),
        migrations.AddField(
            model_name='user',
            name='favorite_songs',
            field=models.ManyToManyField(to='favoritesongs.Song'),
        ),
        migrations.DeleteModel(
            name='FavoriteSong',
        ),
    ]
