# Generated by Django 2.0.2 on 2018-02-13 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('favoritesongs', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='song',
            old_name='title_album',
            new_name='album',
        ),
        migrations.RenameField(
            model_name='song',
            old_name='title_artist',
            new_name='artist',
        ),
        migrations.RenameField(
            model_name='song',
            old_name='title_text',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='email_text',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='name_text',
            new_name='name',
        ),
    ]
