# Generated by Django 2.0.2 on 2018-02-15 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('favoritesongs', '0003_auto_20180215_1548'),
    ]

    operations = [
        migrations.RenameField(
            model_name='favoritesong',
            old_name='song_id',
            new_name='song',
        ),
        migrations.RenameField(
            model_name='favoritesong',
            old_name='user_id',
            new_name='user',
        ),
    ]
